using System;
using System.Threading.Tasks;

namespace VpNet.EventData
{
    /// <summary>
    ///     Represents an async version of <see cref="EventHandler{TEventArgs}" />.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <remarks>
    ///     Because this delegate is intended for use with events fired from <see cref="VirtualParadiseClient" />, the
    ///     <paramref name="sender" /> parameter is constrained to that type.
    /// </remarks>
    public delegate Task AsyncEventHandler<in TEventArgs>(VirtualParadiseClient sender, TEventArgs args)
        where TEventArgs : EventArgs;
}
